server:
  port : 8091
spring:
  datasource:
    #Local
    #url: jdbc:mysql://10.79.56.149:30006/nssfdb
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: nssfusr
    #password: nssfpasswd
    #Cluster
    url: jdbc:mysql://${MYSQL_SERVICE}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    #Local
    #addresses: 10.79.56.149:30227
    #adminAddresses: http://10.79.56.149:30672
    #Cluster
    addresses: ${RABBITMQ_SERVICE}:5672
    adminAddresses: http://${RABBITMQ_SERVICE}:15672
    nodes: rabbit@localhost
    username: guest
    password: guest
    virtual_host: /
    useSSL: false
    channelCacheSize: 100
agenda.default.closure: 60
vote.url.validation.cpf: https://user-info.herokuapp.com/users