server:
  port : 8091
spring:
  datasource:
    url: jdbc:mysql://10.79.56.149:30006/nssfdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nssfusr
    password: nssfpasswd
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQL5Dialect
